//subtitles by various community members
//thanks to Lasertooth, CouldntBeMe, damifortune, icrawfish, dsm5, Opilion, MattMoney, big lumby, TristEndo, DuccBoi, 
//Super_Femicom, awks, DanonZer, 9sphere, Bingies24, and blower5 (that's me!)
SUBTITLES = [
	"Search your worst, find your best!"
	,"Vorted bestest search engine since 1323"
	,"ignoring robots.txt since 2025"
	,"FIND IT ALL HERE"
	//,"I lvoe searxhing things so much i cannot express it enougbh"
	,"56"
	,"&lt;!--Placeholder for search tab subtitle (MAKE SURE TO REPLACE LATER!!!!)--&gt;"
	,"What do you want to search today?"
	,"Have you drank water recently?"
	,"Public Toilet died for this."
	,"Lyceum articles. Battles. BotBrs! You want it? It's yours, my n00b, as long as you have enough boons!"
	,"You sure you don't wanna just click through the site pages randomly until you find what you're looking for?"
	,"Please help they've chained me to this desk and are forcing me to find the results for everyone's searches manually"
	,"battle of the bits search"
	,"botbsearch++"
	,"Do you even search, bro?"
	,"online search game"
	,"It's all just bits, its not even real."
	,"tin can"
	,"This is the greatest search of all time"
	,"Hi, my name is botbsearch."
	,"This is my dance: <(0.0<) (>0.0)> <(0.0<) ^(0.0)^"
	,"┴┬┴┬┤)　┴┬┴┬┤o)　┴┬┴┬┤_o) what are you looking for?"
	,"Teh humanity!!!! x__0"
	,"blaaaah blah blah blah blah blah blah blah blaaaaah"
	,"Wow this palette sucks"
	,"To searcher: yes"
	,"I can quit searching anytime I want."
	,"battleofthebits: \"It's dot com\""
	,"Ohhhhhohohohohohohoho ohhhhh yesssssssss"
	,"Sponsored by Loblast. Have a mighty, mighty day!"
	,"is this wildchip?"
	,"don't forget to smash that search button!"
	,"bringing you scofavs since 2024"
	,"you can tune a chip but you can't chip a tuna"
	,"bringing you the quality search results YOU need"
	,"ask your doctor if battle of the bits search is right for you"
	,"it's fun for the whole family except for when it isn't"
	,"woah man that's crazy I don't even know what that is where am I"
	,"Don't worry. I search for my own entries too."
	,"You favorited your own entry? Wow. That's so embarrassing. How could you?"
	,"Don't forget searching by tags. I use this to find 'megalovania' style entries."
	,"I don't actually get '56' jokes. I just make them to be cool like everyone else."
	,"A toast to the Botbrs long gone! I will listen to all of your entries!"
	,"Which bits would you like today?"
	,"*searching noises*"
	,"search battle of the bits"
	,"The Ask Jeeves of battles"
	,"If your search doesn't produce any results, try giving the screen a stern look"
	,"If your search doesn't produce any results, try making an entry with your search as the title"
	,"The world's first \"search engine\""
	,"Results will be shown once the pneumatic tubes warm up"
	,"\"botbearch\" for short"
	,"Straight Outta Ann Arbor!"
	,"Fact: FakeBit's ham is great year-round!"
	,"Beware monkey licks!"
	,":D"
	,"I forgot"
	,"A new release of OpenMPT is available!"
	,"everything you wanted and so much more"
	
	//---------- part 2 ----------"
	,"Type in that little box right there. Yep. That one. I believe in you."
	,"be oh tee bee dot com"
	,"Filters are for filtering. Searchers are for searchering"
	,"We worked really hard on this. Please use it"
	,"all your emtries are belong to us!!!"
	,"i wont distract u. go ahead and do what u need to do"
	,"Also try emtries.com!"
	,"Tracker?? I hardly know 'er!"
	,"Battle of the fruits would have all the info in the \"lycheeum\" lol"
	,"Do u really know what youre looking for or are you just fucking around? i won't judge"
	,"If your search doesn't produce any results, try curling up into a ball and crying"
	,"I would like to see the results of this search"
	,"You are now searching manually"
	,"But what *is* the deal with forums banning necroposting?"
	,"I would have searched for something different if I were you, but whatever I guess..."
	,"Congratulations! You've just made the 1,000,000,000th search!"
	,"I've fought mudcrabs more fearsome than you!"
	,"Tip: chub dislikes smoke"
	,"Tip: get up on the Hydra's back!"
	,"Must be this tall to search: |------------------🠋-----------|"
	,"Hello? Is it me you're looking for?"
	,"Tip: Results load faster if you close your eyes "
	,"why I oughta!"
	,"Ask your general practitioner if boons are right for you"
	,"For general inquiries, dial: +1 35083904859485039485-0938459-345"
	,"Boon counterfeiting is a serious crime"
	,"Here's how I'll torture you David: #1. The Marrow .fur"
	,"63 68 65 63 6B 20 74 68 65 20 6C 79 63 65 75 6D 20 6E 6F 6F 62"
	,"nice keyboard lol"
	,"Now in 6 exciting new flavors!"
	,"No Loitering"
	,"Post No Bills"
	,"my roflcopter goes soisoisoisoisoisoisoisoisoisoisoi"
	,"*feels the aura*"
	,"Highguard died for this."
	,"Read the lyceum!"
	,"Guilds coming never!"
	,"Listen. You need to help me. They have me back here with a laptop from 2008 and a pack of newports answering these queries. Send help!"
	,"Niko it's Roman, let's go bowling!"
	,"Please puke7, I neeeed this... my entry's kinda homeless"
	,"Contains no AI generated cover art!*"
	,"Be sure to drink your ovaltine!"
	,"I don't give a shit about Viltrum!"
	,"DON'T YOU LECTURE ME WITH YOUR THIRTY DOLLAR HAIRCUT!"
	,"The fortune teller says: excellent luck!"
	,"The fortune teller says: good luck!"
	,"The fortune teller says: bad luck!"
	,"The fortune teller says: terrible luck!"
	,"Snooping as usual I see"
	,"battle of the bits search - a 24/7 service"
	,"BotB gave you 1 nubs."
	,"Press F1 for help!"
	,"the search?"
	,"Eat a bag of poisoned dicks!"
	,"Either avoid being late... or become the greatest Latist of all"
	,"You either die a wildchip or live long enough to see yourself become the fakebit"


	
	//----------blower's arcane pop culture and chiptune references----------
	,"Farm to table search goodness, from jangler and blower."
	,"\"My God, it's full of bits!\""
	,"what is this 8 bit poop crap"
	,"I'm quitting chiptune."
	,"\"No man, you're thinking of beep boo-boo bop, boo-boo bop\""
	,"Bbm Gb Bbm Ab Bbm Gb Bbm Ab Bbm Gb Db Ab Bbm Gb Db Ab Bbm Abm6 Db A C#m Bm Cm Fm"
	,"Asking for extentions since 2005"
	,"So long, and thanks for all the bits"
	,"super cute competition on http"
	,"This is just like Gorbino's Quest. This is the Gorbino's Quest of search"
	,"You have been evaluating REAPER for approximately 484 days."
	,"RIP DESKPOP"
	,"Push the button, and then, turn the knob."
	,"4, 8, 15, 16, 23, 42."
	,"7, 28, 56, 98, 725, 1323."
	,"That's Numberwang!"
	,"Fish can roll."
	,"You missed a tinted rock"

	,"would you like some of this on your that?"
	,"Cannot connect to subtitle service. Check your connection and try again."
	,"hey, I want you to check out this website. Go to www.nfl.com. and just check it out."
	,"These donuts are great! Jelly filled are my favorite! Nothing beats a jelly filled donut."
	,"Could you kick up the 4d3d3d3?"
	,"Consummate V's!"
	,"How do you type with boxing gloves on?"
	,"RISE FROM YOUR GRAVE"
	,"THERE IT IS"
		
	,"Tip: the triangle means major battle."
	,"Tip: hold shift to sort by multiple columns."
	,"Tip: an entry's Scofavs is its score added to its favorite count. Entries with 30 or more Scofavs will appear on the radio."
	
	,"Tip: ask an admin if you need a render replaced, an xhb rescheduled, or a major entry moved to a different format."
	,"Tip: reusing an old avatar only costs 56b."
	,"Tip: reverse thread order, badges ordered by entry count, and other options are available in the settings menu."
	
	,"Tip: switching to your pistol is always faster than reloading."
	,"Tip: shorts are comfortable, and easy to wear."
	,"Tip: as a Medic, it's better to use an ÜberCharge too early than lose it by being killed."
	,"Tip: the power of the switch you have pushed will turn □ into !. Your progress will also be saved."
	,"Tip: to ensure the safe performance of all authorized activities, do not destroy vital testing apparatus."
	,"Tip: the pump over here comes with a truck."
	,"Tip: place the laurels in a silk bag to bring them to life."
	,"Tip: when lava pours out near the sea surface, tremendous volcanic explosions sometimes occur."
	,"Tip: attack its weak point for massive damage."
	,"Tip: No smoking within 20 feet of building entrance."
];