//subtitles by various community members
//thanks to Lasertooth, CouldntBeMe, damifortune, icrawfish, dsm5, Opilion, MattMoney, big lumby, TristEndo, DuccBoi, and blower5 (that's me!)
SUBTITLES = [
	"Search your worst, find your best!"
	,"Vorted bestest search engine since 1323"
	,"ignoring robots.txt since 2025"
	,"FIND IT ALL HERE"
	,"I lvoe searxhing things so much i cannot express it enougbh"
	,"56"
	,"&lt;!--Placeholder for search tab subtitle (MAKE SURE TO REPLACE LATER!!!!)--&gt;"
	,"What do you want to search today?"
	,"Have you drank water recently?"
	,"Public Toilet died for this."
	,"Lyceum articles. Battles. BotBrs! You want it? It's yours, my n00b, as long as you have enough boons!"
	,"You sure you don't wanna just click through the site pages randomly until you find what you're looking for?"
	,"Please help they've chained me to this desk and are forcing me to find the results for everyone's searches manually"
	,"battle of the bits search"
	,"botbsearch++"
	,"Do you even search, bro?"
	,"online search game"
	,"It's all just bits, its not even real."
	,"tin can"
	,"This is the greatest search of all time"
	,"Hi, my name is botbsearch."
	,"This is my dance: <(0.0<) (>0.0)> <(0.0<) ^(0.0)^"
	,"┴┬┴┬┤)　┴┬┴┬┤o)　┴┬┴┬┤_o) what are you looking for?"
	,"Teh humanity!!!! x__0"
	,"blaaaah blah blah blah blah blah blah blah blaaaaah"
	,"Wow this palette sucks"
	,"To searcher: yes"
	,"I can quit searching anytime I want."
	,"battleofthebits: \"It's dot com\""
	,"Ohhhhhohohohohohohoho ohhhhh yesssssssss"
	,"Sponsored by Loblast. Have a mighty, mighty day!"
	,"is this wildchip?"
	,"don't forget to smash that search button!"
	,"bringing you scofavs since 2024"
	,"you can tune a chip but you can't chip a tuna"
	,"bringing you the quality search results YOU need"
	,"ask your doctor if battle of the bits search is right for you"
	,"it's fun for the whole family except for when it isn't"
	,"woah man that's crazy I don't even know what that is where am I"
	,"Don't worry. I search for my own entries too."
	,"You favorited your own entry? Wow. That's so embarrassing. How could you?"
	,"Don't forget searching by tags. I use this to find 'megalovania' style entries."
	,"I don't actually get '56' jokes. I just make them to be cool like everyone else."
	,"A toast to the Botbrs long gone! I will listen to all of your entries!"
	,"Which bits would you like today?"
	,"*searching noises*"
	,"search battle of the bits"
	,"The Ask Jeeves of battles"
	,"If your search doesn't produce any results, try giving the screen a stern look"
	,"If your search doesn't produce any results, try making an entry with your search as the title"
	,"The world's first \"search engine\""
	,"Results will be shown once the pneumatic tubes warm up"
	,"\"botbearch\" for short"
	,"Straight Outta Ann Arbor!"
	,"Fact: FakeBit's ham is great year-round!"
	,"Beware monkey licks!"
	,":D"
	,"I forgot"
	,"A new release of OpenMPT is available!"
	,"everything you wanted and so much more"
	
	//----------blower's arcane pop culture and chiptune references----------
	,"\"My God, it's full of bits!\""
	,"what is this 8 bit poop crap"
	,"I'm quitting chiptune."
	,"\"No man, you're thinking of beep boo-boo bop, boo-boo bop\""
	,"Bbm Gb Bbm Ab Bbm Gb Bbm Ab Bbm Gb Db Ab Bbm Gb Db Ab Bbm Abm6 Db A C#m Bm Cm Fm"
	,"Asking for extentions since 2005"
	,"So long, and thanks for all the bits"
	,"super cute competition on http"
	,"This is just like Gorbino's Quest. This is the Gorbino's Quest of search"
	,"You have been evaluating REAPER for approximately 484 days."
	,"RIP DESKPOP"
	,"Push the button, and then, turn the knob."
	,"4, 8, 15, 16, 23, 42."
	,"7, 28, 56, 98, 725, 1323."
	,"That's Numberwang!"
	
	,"Tip: the triangle means major battle."
	,"Tip: hold shift to sort by multiple columns."
	,"Tip: an entry's Scofavs is its score added to its favorite count. Entries with 30 or more Scofavs will appear on the radio."
	
	,"Tip: ask an admin if you need a render replaced, an xhb rescheduled, or a major entry moved to a different format."
	,"Tip: reusing an old avatar only costs 56b."
	,"Tip: reverse thread order, badges ordered by entry count, and other options are available in the settings menu."
	
	,"Tip: switching to your pistol is always faster than reloading."
	,"Tip: shorts are comfortable, and easy to wear."
	,"Tip: as a Medic, it's better to use an ÜberCharge too early than lose it by being killed."
	,"Tip: the power of the switch you have pushed will turn □ into !. Your progress will also be saved."
	,"Tip: to ensure the safe performance of all authorized activities, do not destroy vital testing apparatus."
	,"Tip: the pump over here comes with a truck."
	,"Tip: place the laurels in a silk bag to bring them to life."
	,"Tip: when lava pours out near the sea surface, tremendous volcanic explosions sometimes occur."
	,"Tip: attack its weak point for massive damage."
];